export const citiesData = {
    "United States": {
        "Alabama": ["Birmingham", "Montgomery", "Mobile", "Huntsville", "Tuscaloosa", "Hoover", "Dothan", "Auburn", "Decatur", "Madison", "Florence", "Gadsden", "Vestavia Hills", "Prattville", "Phenix City", "Homewood", "Anniston", "Bessemer", "Enterprise", "Opelika"],
        "Alaska": ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan", "Wasilla", "Kenai", "Kodiak", "Bethel", "Palmer", "Homer", "Barrow", "Unalaska", "Soldotna", "Valdez", "Nome", "Kotzebue", "Dillingham", "Wrangell", "Petersburg"],
        "Arizona": ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Glendale", "Gilbert", "Tempe", "Peoria", "Surprise", "Yuma", "Avondale", "Goodyear", "Flagstaff", "Buckeye", "Lake Havasu City", "Casa Grande", "Sierra Vista", "Maricopa", "Oro Valley"],
        "Arkansas": ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro", "North Little Rock", "Conway", "Rogers", "Pine Bluff", "Bentonville", "Hot Springs", "Benton", "Sherwood", "Texarkana", "Paragould", "Cabot", "Russellville", "Van Buren", "Jacksonville", "West Memphis"],
        "California": ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento", "Oakland", "Fresno", "Long Beach", "Santa Ana", "Anaheim", "Bakersfield", "Riverside", "Stockton", "Chula Vista", "Irvine", "Fremont", "San Bernardino", "Modesto", "Fontana", "Oxnard", "Moreno Valley", "Huntington Beach", "Glendale", "Santa Clarita", "Garden Grove", "Oceanside", "Rancho Cucamonga", "Santa Rosa", "Ontario", "Lancaster"],
        "Colorado": ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Thornton", "Arvada", "Westminster", "Pueblo", "Centennial", "Boulder", "Greeley", "Longmont", "Loveland", "Grand Junction", "Broomfield", "Castle Rock", "Commerce City", "Parker", "Littleton"],
        "Connecticut": ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury", "Norwalk", "Danbury", "New Britain", "West Hartford", "Greenwich", "Hamden", "Meriden", "Bristol", "Manchester", "West Haven", "Milford", "Middletown", "Norwich", "Shelton", "Torrington"],
        "Delaware": ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna", "Milford", "Seaford", "Georgetown", "Elsmere", "New Castle", "Bear", "Brookside", "Pike Creek Valley", "Hockessin", "Glasgow", "Claymont", "Pike Creek", "Edgemoor", "North Star", "Woodside East"],
        "Florida": ["Miami", "Tampa", "Orlando", "Jacksonville", "St. Petersburg", "Hialeah", "Tallahassee", "Fort Lauderdale", "Port St. Lucie", "Cape Coral", "Pembroke Pines", "Hollywood", "Miramar", "Gainesville", "Coral Springs", "Miami Gardens", "Clearwater", "Palm Bay", "West Palm Beach", "Pompano Beach", "Lakeland", "Davie", "Miami Beach", "Sunrise", "Plantation"],
        "Georgia": ["Atlanta", "Augusta", "Columbus", "Macon", "Savannah", "Athens", "Sandy Springs", "Roswell", "Johns Creek", "Albany", "Warner Robins", "Alpharetta", "Marietta", "Valdosta", "Smyrna", "Dunwoody", "Rome", "East Point", "Peachtree Corners", "Gainesville"],
        "Hawaii": ["Honolulu", "Pearl City", "Hilo", "Kailua", "Waipahu", "Kaneohe", "Mililani Town", "Kahului", "Ewa Gentry", "Mililani Mauka", "Kihei", "Wahiawa", "Ewa Beach", "Royal Kunia", "Kapolei", "Aiea", "Halawa", "Wailuku", "Waimalu", "Kailua-Kona"],
        "Idaho": ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello", "Caldwell", "Coeur d'Alene", "Twin Falls", "Lewiston", "Post Falls", "Rexburg", "Eagle", "Chubbuck", "Ammon", "Hayden", "Mountain Home", "Kuna", "Jerome", "Blackfoot", "Burley"],
        "Illinois": ["Chicago", "Aurora", "Rockford", "Joliet", "Naperville", "Springfield", "Peoria", "Elgin", "Waukegan", "Cicero", "Champaign", "Bloomington", "Arlington Heights", "Evanston", "Decatur", "Schaumburg", "Bolingbrook", "Palatine", "Skokie", "Des Plaines"],
        "Indiana": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel", "Fishers", "Bloomington", "Hammond", "Gary", "Muncie", "Lafayette", "Terre Haute", "Kokomo", "Anderson", "Noblesville", "Greenwood", "Elkhart", "Mishawaka", "Lawrence", "Jeffersonville"],
        "Iowa": ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City", "Waterloo", "Council Bluffs", "Ames", "West Des Moines", "Dubuque", "Ankeny", "Urbandale", "Cedar Falls", "Marion", "Bettendorf", "Mason City", "Marshalltown", "Clinton", "Burlington", "Ottumwa"],
        "Kansas": ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe", "Lawrence", "Shawnee", "Manhattan", "Lenexa", "Salina", "Hutchinson", "Leavenworth", "Leawood", "Dodge City", "Garden City", "Emporia", "Junction City", "Derby", "Prairie Village", "Hays"],
        "Kentucky": ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington", "Richmond", "Georgetown", "Florence", "Hopkinsville", "Nicholasville", "Elizabethtown", "Henderson", "Frankfort", "Jeffersontown", "Independence", "Paducah", "Radcliff", "Ashland", "Madisonville", "Murray"],
        "Louisiana": ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles", "Kenner", "Bossier City", "Monroe", "Alexandria", "Houma", "Marrero", "Bayou Cane", "Prairieville", "Central", "Laplace", "Slidell", "Ruston", "Sulphur", "Hammond", "Natchitoches"],
        "Maine": ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn", "Biddeford", "Sanford", "Saco", "Augusta", "Westbrook", "Waterville", "Presque Isle", "Gorham", "Brewer", "Cape Elizabeth", "Caribou", "Orono", "Old Town", "Bath", "Ellsworth"],
        "Maryland": ["Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie", "Hagerstown", "Annapolis", "College Park", "Salisbury", "Laurel", "Greenbelt", "Cumberland", "Westminster", "Hyattsville", "Takoma Park", "Easton", "Aberdeen", "Elkton", "Havre de Grace", "Cambridge"],
        "Massachusetts": ["Boston", "Worcester", "Springfield", "Lowell", "Cambridge", "New Bedford", "Brockton", "Quincy", "Lynn", "Fall River", "Newton", "Lawrence", "Somerville", "Framingham", "Haverhill", "Waltham", "Malden", "Brookline", "Plymouth", "Medford"],
        "Michigan": ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Lansing", "Ann Arbor", "Flint", "Dearborn", "Livonia", "Westland", "Troy", "Farmington Hills", "Kalamazoo", "Wyoming", "Southfield", "Rochester Hills", "Taylor", "Pontiac", "St. Clair Shores", "Royal Oak"],
        "Minnesota": ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington", "Brooklyn Park", "Plymouth", "St. Cloud", "Eagan", "Woodbury", "Maple Grove", "Eden Prairie", "Coon Rapids", "Burnsville", "Blaine", "Lakeville", "Minnetonka", "Apple Valley", "Edina", "St. Louis Park"],
        "Mississippi": ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi", "Meridian", "Tupelo", "Greenville", "Olive Branch", "Horn Lake", "Clinton", "Pearl", "Ridgeland", "Starkville", "Columbus", "Vicksburg", "Pascagoula", "Ocean Springs", "Madison", "Gautier"],
        "Missouri": ["Kansas City", "Saint Louis", "Springfield", "Independence", "Columbia", "Lee's Summit", "O'Fallon", "St. Joseph", "St. Charles", "St. Peters", "Blue Springs", "Florissant", "Joplin", "Chesterfield", "Jefferson City", "Cape Girardeau", "Oakville", "Wildwood", "University City", "Ballwin"],
        "Montana": ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte", "Helena", "Kalispell", "Havre", "Anaconda", "Miles City", "Belgrade", "Livingston", "Laurel", "Whitefish", "Lewistown", "Sidney", "Glendive", "Hamilton", "Columbia Falls", "Polson"],
        "Nebraska": ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney", "Fremont", "Hastings", "North Platte", "Norfolk", "Columbus", "Papillion", "La Vista", "Scottsbluff", "South Sioux City", "Beatrice", "Chalco", "Alliance", "York", "McCook", "Nebraska City"],
        "Nevada": ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks", "Carson City", "Fernley", "Elko", "Mesquite", "Boulder City", "Fallon", "Winnemucca", "West Wendover", "Ely", "Yerington", "Carlin", "Lovelock", "Wells", "Caliente", "Hawthorne"],
        "New Hampshire": ["Manchester", "Nashua", "Concord", "Derry", "Rochester", "Salem", "Dover", "Merrimack", "Londonderry", "Hudson", "Keene", "Bedford", "Portsmouth", "Goffstown", "Laconia", "Hampton", "Milford", "Durham", "Exeter", "Windham"],
        "New Jersey": ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison", "Woodbridge", "Lakewood", "Toms River", "Hamilton", "Trenton", "Clifton", "Camden", "Brick", "East Orange", "Passaic", "Union City", "Bayonne", "East Brunswick", "Vineland", "New Brunswick"],
        "New Mexico": ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell", "Farmington", "Clovis", "Hobbs", "Alamogordo", "Carlsbad", "Gallup", "Deming", "Los Alamos", "Chaparral", "Sunland Park", "Las Vegas", "Portales", "North Valley", "Silver City", "Artesia"],
        "New York": ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany", "New Rochelle", "Mount Vernon", "Schenectady", "Utica", "White Plains", "Hempstead", "Troy", "Niagara Falls", "Binghamton", "Freeport", "Valley Stream", "Long Beach", "Rome", "Watertown"],
        "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville", "Cary", "Wilmington", "High Point", "Greenville", "Asheville", "Concord", "Gastonia", "Jacksonville", "Chapel Hill", "Rocky Mount", "Burlington", "Wilson", "Huntersville", "Kannapolis"],
        "North Dakota": ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo", "Williston", "Dickinson", "Mandan", "Jamestown", "Wahpeton", "Devils Lake", "Valley City", "Grafton", "Watford City", "Beulah", "Rugby", "Carrington", "New Town", "Bottineau", "Hazen"],
        "Ohio": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton", "Parma", "Canton", "Youngstown", "Lorain", "Hamilton", "Springfield", "Kettering", "Elyria", "Lakewood", "Cuyahoga Falls", "Middletown", "Euclid", "Newark", "Mansfield"],
        "Oklahoma": ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Lawton", "Edmond", "Moore", "Midwest City", "Enid", "Stillwater", "Muskogee", "Bartlesville", "Owasso", "Shawnee", "Ponca City", "Ardmore", "Duncan", "Bixby", "McAlester", "Tahlequah"],
        "Oregon": ["Portland", "Eugene", "Salem", "Gresham", "Hillsboro", "Bend", "Beaverton", "Medford", "Springfield", "Corvallis", "Albany", "Tigard", "Lake Oswego", "Keizer", "Grants Pass", "Oregon City", "McMinnville", "Redmond", "Tualatin", "West Linn"],
        "Pennsylvania": ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Scranton", "Bethlehem", "Lancaster", "Harrisburg", "Altoona", "York", "State College", "Wilkes-Barre", "Chester", "Williamsport", "Easton", "Lebanon", "Hazleton", "New Castle", "Johnstown"],
        "Rhode Island": ["Providence", "Warwick", "Cranston", "Pawtucket", "East Providence", "Woonsocket", "Newport", "Central Falls", "Westerly", "North Providence", "West Warwick", "Johnston", "North Kingstown", "South Kingstown", "Coventry", "Cumberland", "Lincoln", "Smithfield", "Barrington", "Bristol"],
        "South Carolina": ["Columbia", "Charleston", "North Charleston", "Mount Pleasant", "Rock Hill", "Greenville", "Summerville", "Sumter", "Goose Creek", "Hilton Head Island", "Florence", "Spartanburg", "Anderson", "Myrtle Beach", "Greer", "Greenwood", "Aiken", "North Augusta", "Easley", "Simpsonville"],
        "South Dakota": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown", "Mitchell", "Yankton", "Pierre", "Huron", "Spearfish", "Vermillion", "Madison", "Sturgis", "Lead", "Hot Springs", "Deadwood", "Milbank", "Winner", "Mobridge", "Belle Fourche"],
        "Tennessee": ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro", "Franklin", "Jackson", "Johnson City", "Bartlett", "Hendersonville", "Kingsport", "Collierville", "Smyrna", "Cleveland", "Brentwood", "Germantown", "Columbia", "Spring Hill", "La Vergne"],
        "Texas": ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Lubbock", "Laredo", "Garland", "Irving", "Amarillo", "Grand Prairie", "Brownsville", "McKinney", "Frisco", "Pasadena", "Killeen", "Mesquite", "McAllen", "Carrollton", "Midland", "Waco", "Round Rock", "Richardson", "Pearland", "College Station", "Denton"],
        "Utah": ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem", "Sandy", "Ogden", "St. George", "Layton", "Taylorsville", "South Jordan", "Lehi", "Logan", "Murray", "Draper", "Bountiful", "Riverton", "Roy", "Pleasant Grove", "Tooele"],
        "Vermont": ["Burlington", "Essex", "South Burlington", "Colchester", "Rutland", "Bennington", "Brattleboro", "Milton", "Hartford", "Williston", "Middlebury", "Barre", "Montpelier", "St. Albans", "Winooski", "Northfield", "St. Johnsbury", "Shelburne", "Swanton", "Springfield"],
        "Virginia": ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News", "Alexandria", "Hampton", "Portsmouth", "Suffolk", "Roanoke", "Lynchburg", "Harrisonburg", "Leesburg", "Charlottesville", "Danville", "Blacksburg", "Manassas", "Petersburg", "Fredericksburg", "Winchester"],
        "Washington": ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kent", "Everett", "Renton", "Yakima", "Federal Way", "Spokane Valley", "Bellingham", "Kennewick", "Auburn", "Pasco", "Marysville", "Lakewood", "Redmond", "Shoreline", "Richland"],
        "West Virginia": ["Charleston", "Huntington", "Parkersburg", "Morgantown", "Wheeling", "Martinsburg", "Fairmont", "Beckley", "Clarksburg", "Lewisburg", "Buckhannon", "Charles Town", "Bridgeport", "Hurricane", "Ranson", "Keyser", "Shepherdstown", "South Charleston", "St. Albans", "Nitro"],
        "Wisconsin": ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton", "Waukesha", "Eau Claire", "Oshkosh", "Janesville", "West Allis", "La Crosse", "Sheboygan", "Wauwatosa", "Fond du Lac", "New Berlin", "Wausau", "Brookfield", "Greenfield", "Beloit"],
        "Wyoming": ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs", "Sheridan", "Green River", "Evanston", "Riverton", "Jackson", "Cody", "Rawlins", "Lander", "Torrington", "Powell", "Douglas", "Worland", "Buffalo", "Newcastle", "Wheatland"],
        "District of Columbia": ["Washington"]
    },

    "India": {
        "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Rajahmundry", "Tirupati", "Kadapa", "Kakinada", "Anantapur", "Vizianagaram", "Eluru", "Ongole", "Nandyal", "Machilipatnam", "Adoni", "Tenali", "Chittoor", "Hindupur", "Proddatur"],
        "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tezpur", "Bomdila", "Ziro", "Along", "Basar", "Tezu", "Namsai", "Changlang", "Khonsa", "Longding", "Anini", "Tawang", "Seppa", "Yingkiong", "Roing", "Daporijo", "Koloriang"],
        "Assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tinsukia", "Tezpur", "Bongaigaon", "Karimganj", "Sivasagar", "Goalpara", "Barpeta", "North Lakhimpur", "Mangaldoi", "Haflong", "Kokrajhar", "Hailakandi", "Morigaon", "Nalbari", "Dhubri"],
        "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia", "Darbhanga", "Bihar Sharif", "Arrah", "Begusarai", "Katihar", "Munger", "Chhapra", "Danapur", "Saharsa", "Sasaram", "Hajipur", "Dehri", "Siwan", "Motihari", "Nawada"],
        "Chhattisgarh": ["Raipur", "Bhilai", "Korba", "Bilaspur", "Durg", "Rajnandgaon", "Jagdalpur", "Raigarh", "Ambikapur", "Mahasamund", "Dhamtari", "Chirmiri", "Janjgir", "Sakti", "Tilda Newra", "Mungeli", "Manendragarh", "Naila Janjgir", "Bhatapara", "Dalli-Rajhara"],
        "Goa": ["Panaji", "Vasco da Gama", "Margao", "Mapusa", "Ponda", "Bicholim", "Curchorem", "Sanquelim", "Cuncolim", "Canacona", "Quepem", "Sanguem", "Pernem", "Sattari", "Dharbandora", "Aldona", "Arambol", "Assagao", "Benaulim", "Calangute"],
        "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar", "Anand", "Bharuch", "Junagadh", "Nadiad", "Morbi", "Mahesana", "Bhuj", "Porbandar", "Palanpur", "Vapi", "Godhra", "Patan", "Kalol"],
        "Haryana": ["Faridabad", "Gurgaon", "Panipat", "Ambala", "Yamunanagar", "Rohtak", "Hisar", "Karnal", "Sonipat", "Panchkula", "Bhiwani", "Sirsa", "Bahadurgarh", "Jind", "Thanesar", "Kaithal", "Rewari", "Narnaul", "Pundri", "Kosli"],
        "Himachal Pradesh": ["Shimla", "Dharamshala", "Solan", "Mandi", "Palampur", "Kullu", "Hamirpur", "Una", "Bilaspur", "Chamba", "Kangra", "Kinnaur", "Lahaul and Spiti", "Sirmaur", "Nahan", "Baddi", "Parwanoo", "Kasauli", "Manali", "Dalhousie"],
        "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar", "Phusro", "Hazaribagh", "Giridih", "Ramgarh", "Medininagar", "Chirkunda", "Pakaur", "Chaibasa", "Mihijam", "Chatra", "Gumla", "Dumka", "Sahibganj", "Lohardaga", "Simdega"],
        "Karnataka": ["Bangalore", "Mysore", "Hubli", "Mangalore", "Belgaum", "Gulbarga", "Davanagere", "Bellary", "Bijapur", "Shimoga", "Tumkur", "Raichur", "Bidar", "Hospet", "Hassan", "Gadag-Betageri", "Udupi", "Bhadravati", "Chitradurga", "Kolar"],
        "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Palakkad", "Alappuzha", "Malappuram", "Kannur", "Kasaragod", "Pathanamthitta", "Idukki", "Ernakulam", "Wayanad", "Kottayam", "Thalassery", "Kayamkulam", "Kunnamkulam", "Ottappalam", "Tirur"],
        "Madhya Pradesh": ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain", "Sagar", "Dewas", "Satna", "Ratlam", "Rewa", "Murwara", "Singrauli", "Burhanpur", "Khandwa", "Bhind", "Chhindwara", "Guna", "Shivpuri", "Vidisha", "Chhatarpur"],
        "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Solapur", "Amravati", "Kolhapur", "Sangli", "Malegaon", "Akola", "Latur", "Dhule", "Ahmednagar", "Chandrapur", "Parbhani", "Jalgaon", "Bhiwandi", "Nanded"],
        "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Kakching", "Ukhrul", "Senapati", "Tamenglong", "Chandel", "Jiribam", "Kangpokpi", "Tengnoupal", "Kamjong", "Noney", "Pherzawl", "Moreh", "Lilong", "Mayang Imphal", "Yairipok", "Wangjing"],
        "Meghalaya": ["Shillong", "Tura", "Jowai", "Nongpoh", "Baghmara", "Williamnagar", "Nongstoin", "Mawkyrwat", "Resubelpara", "Ampati", "Khliehriat", "Mairang", "Mawsynram", "Cherrapunji", "Dawki", "Bholaganj", "Umiam", "Byrnihat", "Ri-Bhoi", "Nongthymmai"],
        "Mizoram": ["Aizawl", "Lunglei", "Saiha", "Champhai", "Kolasib", "Serchhip", "Mamit", "Lawngtlai", "Saitual", "Khawzawl", "Hnahthial", "Bairabi", "North Vanlaiphai", "Tlabung", "Zawlnuam", "Thenzawl", "Darlawn", "Khawhai", "Tuipang", "Bungtlang"],
        "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha", "Zunheboto", "Phek", "Kiphire", "Longleng", "Peren", "Mon", "Noklak", "Chumukedima", "Pfutsero", "Jalukie", "Tuli", "Aboi", "Changtongya", "Longkhim", "Tizit"],
        "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Balasore", "Bhadrak", "Baripada", "Jharsuguda", "Jeypore", "Barbil", "Khordha", "Sunabeda", "Rayagada", "Kendrapara", "Nabarangpur", "Paradip", "Bhawanipatna", "Dhenkanal"],
        "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Firozpur", "Batala", "Pathankot", "Moga", "Abohar", "Malerkotla", "Khanna", "Phagwara", "Muktsar", "Barnala", "Rajpura", "Hoshiarpur", "Kapurthala", "Faridkot"],
        "Rajasthan": ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer", "Udaipur", "Bhilwara", "Alwar", "Bharatpur", "Sikar", "Pali", "Sri Ganganagar", "Kishangarh", "Baran", "Dhaulpur", "Tonk", "Beawar", "Hanumangarh", "Gangapur City", "Banswara"],
        "Sikkim": ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Rangpo", "Jorethang", "Nayabazar", "Rhenock", "Singtam", "Pakyong", "Ravangla", "Yuksom", "Lachung", "Lachen", "Pelling", "Soreng", "Chungthang", "Dentam", "Kalimpong", "Melli"],
        "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Tiruppur", "Vellore", "Erode", "Thoothukudi", "Dindigul", "Thanjavur", "Ranipet", "Sivakasi", "Karur", "Udhagamandalam", "Hosur", "Nagercoil", "Kanchipuram", "Kumarakonam"],
        "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Khammam", "Karimnagar", "Ramagundam", "Mahbubnagar", "Nalgonda", "Adilabad", "Suryapet", "Miryalaguda", "Jagtial", "Mancherial", "Nirmal", "Kothagudem", "Bodhan", "Sangareddy", "Metpally", "Zaheerabad", "Medak"],
        "Tripura": ["Agartala", "Dharmanagar", "Udaipur", "Kailasahar", "Belonia", "Khowai", "Ambassa", "Kamalpur", "Sabroom", "Sonamura", "Kumarghat", "Ranirbazar", "Bishalgarh", "Teliamura", "Jirania", "Mohanpur", "Melaghar", "Amarpur", "Santirbazar", "Kanchanpur"],
        "Uttar Pradesh": ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Meerut", "Varanasi", "Allahabad", "Bareilly", "Aligarh", "Moradabad", "Saharanpur", "Gorakhpur", "Noida", "Firozabad", "Jhansi", "Muzaffarnagar", "Mathura", "Rampur", "Shahjahanpur", "Farrukhabad"],
        "Uttarakhand": ["Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rudrapur", "Kashipur", "Rishikesh", "Kotdwar", "Ramnagar", "Manglaur", "Laksar", "Pauri", "Srinagar", "Pithoragarh", "Bageshwar", "Champawat", "Almora", "Nainital", "Mussoorie", "Lansdowne"],
        "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Malda", "Baharampur", "Habra", "Kharagpur", "Shantipur", "Dankuni", "Dhulian", "Ranaghat", "Haldia", "Raiganj", "Krishnanagar", "Nabadwip", "Medinipur", "Jalpaiguri", "Balurghat"],
        "Andaman and Nicobar Islands": ["Port Blair", "Bamboo Flat", "Garacharma", "Diglipur", "Mayabunder", "Rangat", "Havelock Island", "Neil Island", "Car Nicobar", "Nancowry"],
        "Chandigarh": ["Chandigarh", "Mani Majra", "Dhanas", "Maloya", "Burail", "Raipur Khurd", "Raipur Kalan", "Kaimbwala", "Hallomajra", "Kishangarh"],
        "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Diu", "Silvassa", "Naroli", "Rampura", "Khanvel", "Samarvarni", "Dunetha", "Kachigam", "Amli"],
        "Delhi": ["New Delhi", "Delhi", "North Delhi", "South Delhi", "East Delhi", "West Delhi", "Central Delhi", "North East Delhi", "North West Delhi", "South East Delhi", "South West Delhi"],
        "Jammu and Kashmir": ["Srinagar", "Jammu", "Baramulla", "Anantnag", "Sopore", "KathuaUdhampur", "Punch", "Rajouri", "Kupwara", "Budgam", "Ganderbal", "Pulwama", "Shopian", "Bandipora", "Kulgam", "Ramban", "Kishtwar", "Doda", "Reasi", "Samba"],
        "Ladakh": ["Leh", "Kargil", "Nubra", "Changthang", "Zanskar", "Drass", "Sankoo", "Turtuk", "Hunder", "Diskit"],
        "Lakshadweep": ["Kavaratti", "Agatti", "Minicoy", "Amini", "Andrott", "Kalpeni", "Kadmat", "Kiltan", "Chetlat", "Bitra"],
        "Puducherry": ["Puducherry", "Karaikal", "Mahe", "Yanam", "Villianur", "Ariyankuppam", "Bahour", "Nettapakkam", "Mannadipet", "Ozhukarai"]
    },

    "Canada": {
        "Alberta": ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "Medicine Hat", "Grande Prairie", "Airdrie", "Spruce Grove", "Leduc", "Lloydminster", "Camrose", "Fort McMurray", "Lacombe", "Wetaskiwin", "Cold Lake", "Cochrane", "Beaumont", "Stony Plain", "Hinton", "Canmore"],
        "British Columbia": ["Vancouver", "Victoria", "Surrey", "Burnaby", "Richmond", "Abbotsford", "Coquitlam", "Kelowna", "Saanich", "Delta", "Langley", "Kamloops", "Nanaimo", "Prince George", "Chilliwack", "Vernon", "New Westminster", "North Vancouver", "Penticton", "White Rock"],
        "Manitoba": ["Winnipeg", "Brandon", "Steinbach", "Thompson", "Portage la Prairie", "Winkler", "Selkirk", "Morden", "Dauphin", "The Pas", "Flin Flon", "Gimli", "Stonewall", "Neepawa", "Carman", "Virden", "Minnedosa", "Killarney", "Souris", "Boissevain"],
        "New Brunswick": ["Saint John", "Moncton", "Fredericton", "Dieppe", "Riverview", "Miramichi", "Edmundston", "Campbellton", "Rothesay", "Quispamsis", "Bathurst", "Sackville", "Sussex", "Caraquet", "Grand Falls", "Woodstock", "Shediac", "Oromocto", "Dalhousie", "St. Stephen"],
        "Newfoundland and Labrador": ["St. John's", "Mount Pearl", "Corner Brook", "Conception Bay South", "Paradise", "Grand Falls-Windsor", "Happy Valley-Goose Bay", "Labrador City", "Stephenville", "Torbay", "Gander", "Portugal Cove-St. Philip's", "Clarenville", "Bay Roberts", "Carbonear", "Deer Lake", "Marystown", "Channel-Port aux Basques", "Placentia", "Bonavista"],
        "Northwest Territories": ["Yellowknife", "Hay River", "Inuvik", "Fort Smith", "Behchoko", "Fort Simpson", "Norman Wells", "Iqaluit", "Rankin Inlet", "Arviat", "Baker Lake", "Cambridge Bay", "Igloolik", "Pond Inlet", "Cape Dorset", "Pangnirtung", "Gjoa Haven", "Kugluktuk", "Taloyoak", "Repulse Bay"],
        "Nova Scotia": ["Halifax", "Sydney", "Dartmouth", "Truro", "New Glasgow", "Glace Bay", "Kentville", "Amherst", "Yarmouth", "Bridgewater", "New Waterford", "Antigonish", "Wolfville", "Stellarton", "Windsor", "Liverpool", "Digby", "Oxford", "Pictou", "Mahone Bay"],
        "Nunavut": ["Iqaluit", "Rankin Inlet", "Arviat", "Baker Lake", "Cambridge Bay", "Igloolik", "Pond Inlet", "Cape Dorset", "Pangnirtung", "Gjoa Haven", "Kugluktuk", "Taloyoak", "Repulse Bay", "Coral Harbour", "Chesterfield Inlet", "Whale Cove", "Naujaat", "Hall Beach", "Arctic Bay", "Clyde River"],
        "Ontario": ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London", "Markham", "Vaughan", "Kitchener", "Windsor", "Richmond Hill", "Oakville", "Burlington", "Oshawa", "Barrie", "St. Catharines", "Cambridge", "Kingston", "Whitby", "Guelph", "Thunder Bay", "Waterloo", "Sudbury", "Sault Ste. Marie", "Sarnia", "Peterborough", "Niagara Falls", "Brantford", "Pickering", "Ajax"],
        "Prince Edward Island": ["Charlottetown", "Summerside", "Stratford", "Cornwall", "Montague", "Kensington", "Souris", "Alberton", "Georgetown", "Tignish", "O'Leary", "Borden-Carleton", "Crapaud", "Hunter River", "Wellington", "Brackley", "Miltonvale Park", "North Rustico", "Victoria", "Cavendish"],
        "Quebec": ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil", "Sherbrooke", "Saguenay", "Lévis", "Trois-Rivières", "Terrebonne", "Saint-Jean-sur-Richelieu", "Repentigny", "Brossard", "Drummondville", "Saint-Jérôme", "Granby", "Blainville", "Saint-Hyacinthe", "Shawinigan", "Dollard-des-Ormeaux"],
        "Saskatchewan": ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw", "Swift Current", "Yorkton", "North Battleford", "Estevan", "Weyburn", "Lloydminster", "Martensville", "Warman", "Humboldt", "Melfort", "Kindersley", "Meadow Lake", "Melville", "Tisdale", "Rosetown", "Carlyle"],
        "Yukon": ["Whitehorse", "Dawson City", "Watson Lake", "Haines Junction", "Mayo", "Carmacks", "Faro", "Ross River", "Teslin", "Pelly Crossing", "Beaver Creek", "Destruction Bay", "Burwash Landing", "Old Crow", "Eagle Plains", "Swift River", "Champagne", "Tagish", "Carcross", "Little Salmon"]
    },

    "United Kingdom": {
        "England": ["London", "Birmingham", "Manchester", "Liverpool", "Leeds", "Sheffield", "Bristol", "Newcastle", "Nottingham", "Leicester", "Coventry", "Bradford", "Stoke-on-Trent", "Wolverhampton", "Plymouth", "Derby", "Southampton", "Swansea", "Salford", "Aberdeen", "Westminster", "Portsmouth", "York", "Peterborough", "Dundee", "Lancaster", "Oxford", "Newport", "Preston", "St Albans", "Norwich", "Chester", "Cambridge", "Salisbury", "Exeter", "Colchester", "Chelmsford", "Gloucester", "Worcester", "Winchester", "Bath", "Hereford", "Carlisle", "Durham", "Chichester", "Ely", "Truro", "Wells", "Ripon", "Wakefield", "Lichfield"],
        "Scotland": ["Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Stirling", "Perth", "Inverness", "Paisley", "East Kilbride", "Livingston", "Hamilton", "Cumbernauld", "Kirkcaldy", "Dunfermline", "Ayr", "Kilmarnock", "Greenock", "Coatbridge", "Glenrothes", "Airdrie", "Falkirk", "Motherwell", "Irvine", "Wishaw", "Dumfries", "Rutherglen", "Cambuslang", "Bearsden", "Newton Mearns", "Bishopbriggs"],
        "Wales": ["Cardiff", "Swansea", "Newport", "Wrexham", "Barry", "Caerphilly", "Bridgend", "Neath", "Port Talbot", "Cwmbran", "Rhondda", "Merthyr Tydfil", "Llanelli", "Colwyn Bay", "Flint", "Bangor", "Carmarthen", "Pontypridd", "Ebbw Vale", "Maesteg", "Aberdare", "Bargoed", "Penarth", "Prestatyn", "Conwy", "Haverfordwest", "Aberystwyth", "Newtown", "Welshpool", "Brecon"],
        "Northern Ireland": ["Belfast", "Derry", "Lisburn", "Newtownabbey", "Bangor", "Craigavon", "Castlereagh", "Ballymena", "Newtownards", "Carrickfergus", "Coleraine", "Omagh", "Larne", "Strabane", "Limavady", "Enniskillen", "Antrim", "Armagh", "Dungannon", "Cookstown", "Downpatrick", "Ballymoney", "Comber", "Holywood", "Portstewart", "Newcastle", "Ballycastle", "Magherafelt", "Portrush", "Hillsborough"]
    },

    "Australia": {
        "New South Wales": ["Sydney", "Newcastle", "Wollongong", "Maitland", "Wagga Wagga", "Albury", "Port Macquarie", "Tamworth", "Orange", "Dubbo", "Queanbeyan", "Bathurst", "Nowra", "Warrnambool", "Lismore", "Bowral", "Armidale", "Taree", "Nelson Bay", "Goulburn", "Cessnock", "Griffith", "Broken Hill", "Coffs Harbour", "Ballina", "Tweed Heads", "Byron Bay", "Mudgee", "Parkes", "Singleton"],
        "Victoria": ["Melbourne", "Geelong", "Ballarat", "Bendigo", "Shepparton", "Mildura", "Latrobe City", "Warrnambool", "Horsham", "Wodonga", "Echuca", "Swan Hill", "Wangaratta", "Sale", "Bairnsdale", "Colac", "Ararat", "Stawell", "Hamilton", "Portland", "Castlemaine", "Kyneton", "Daylesford", "Lorne", "Apollo Bay", "Bright", "Mount Eliza", "Frankston", "Dandenong", "Pakenham"],
        "Queensland": ["Brisbane", "Gold Coast", "Townsville", "Cairns", "Toowoomba", "Rockhampton", "Mackay", "Bundaberg", "Hervey Bay", "Gladstone", "Sunshine Coast", "Ipswich", "Logan City", "Redland City", "Moreton Bay", "Mount Isa", "Maryborough", "Gympie", "Warwick", "Chinchilla", "Roma", "Charleville", "Longreach", "Emerald", "Clermont", "Bowen", "Ayr", "Innisfail", "Mareeba", "Atherton"],
        "Western Australia": ["Perth", "Fremantle", "Bunbury", "Geraldton", "Kalgoorlie", "Mandurah", "Albany", "Rockingham", "Joondalup", "Armadale", "Wanneroo", "Stirling", "Cockburn", "Gosnells", "Melville", "Bayswater", "Canning", "Jandakot", "Kalamunda", "Mundaring", "Swan", "Chittering", "Gingin", "Dandaragan", "Victoria Park", "Subiaco", "Nedlands", "Cottesloe", "Claremont", "Peppermint Grove"],
        "South Australia": ["Adelaide", "Mount Gambier", "Whyalla", "Murray Bridge", "Port Lincoln", "Port Augusta", "Port Pirie", "Victor Harbor", "Gawler", "Mount Barker", "Berri", "Renmark", "Loxton", "Kadina", "Clare", "Tanunda", "Nuriootpa", "Angaston", "Hahndorf", "Strathalbyn", "Yankalilla", "Kingscote", "Coober Pedy", "Roxby Downs", "Ceduna", "Bordertown", "Naracoorte", "Millicent", "Penola", "Keith"],
        "Tasmania": ["Hobart", "Launceston", "Devonport", "Burnie", "Ulverstone", "Wynyard", "George Town", "Smithton", "Queenstown", "Strahan", "New Norfolk", "Richmond", "Sorell", "Kingston", "Huonville", "Dover", "Swansea", "Bicheno", "St Helens", "Scottsdale", "Deloraine", "Sheffield", "Penguin", "Stanley", "Currie", "Whitemark", "Flinders Island", "King Island", "Bruny Island", "Maria Island"],
        "Northern Territory": ["Darwin", "Alice Springs", "Palmerston", "Katherine", "Nhulunbuy", "Tennant Creek", "Jabiru", "Yulara", "Pine Creek", "Mataranka", "Daly Waters", "Elliott", "Newcastle Waters", "Larrimah", "Adelaide River", "Batchelor", "Humpty Doo", "Howard Springs", "Berry Springs", "Coolalinga", "Virginia", "Noonamah", "Girraween", "Livingstone", "Marrakai", "McMinns Lagoon", "Lambells Lagoon", "Knuckey Lagoon", "Fly Creek", "Blackmore"],
        "Australian Capital Territory": ["Canberra", "Gungahlin", "Tuggeranong", "Woden", "Belconnen", "Weston Creek", "Molonglo Valley", "Jerrabomberra", "Queanbeyan", "Hall", "Tharwa", "Uriarra", "Paddys River", "Naas", "Gudgenby", "Orroral", "Honeysuckle Creek", "Tidbinbilla", "Cotter", "Stromlo"]
    },

    "Germany": {
        "Baden-Württemberg": ["Stuttgart", "Mannheim", "Karlsruhe", "Freiburg", "Heidelberg"],
        "Bavaria": ["Munich", "Nuremberg", "Augsburg", "Würzburg", "Regensburg"],
        "Berlin": ["Berlin"],
        "Brandenburg": ["Potsdam", "Cottbus", "Brandenburg", "Frankfurt (Oder)", "Oranienburg"],
        "Bremen": ["Bremen", "Bremerhaven"],
        "Hamburg": ["Hamburg"],
        "Hesse": ["Frankfurt am Main", "Wiesbaden", "Kassel", "Darmstadt", "Offenbach"],
        "Lower Saxony": ["Hanover", "Braunschweig", "Oldenburg", "Osnabrück", "Wolfsburg"],
        "Mecklenburg-Vorpommern": ["Rostock", "Schwerin", "Neubrandenburg", "Stralsund", "Greifswald"],
        "North Rhine-Westphalia": ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Duisburg"],
        "Rhineland-Palatinate": ["Mainz", "Ludwigshafen", "Koblenz", "Trier", "Kaiserslautern"],
        "Saarland": ["Saarbrücken", "Neunkirchen", "Homburg", "Völklingen", "Sankt Ingbert"],
        "Saxony": ["Dresden", "Leipzig", "Chemnitz", "Zwickau", "Plauen"],
        "Saxony-Anhalt": ["Magdeburg", "Halle", "Dessau", "Wittenberg", "Stendal"],
        "Schleswig-Holstein": ["Kiel", "Lübeck", "Flensburg", "Neumünster", "Norderstedt"],
        "Thuringia": ["Erfurt", "Jena", "Gera", "Weimar", "Gotha"]
    },

    "France": {
        "Île-de-France": ["Paris", "Boulogne-Billancourt", "Saint-Denis", "Argenteuil", "Montreuil"],
        "Provence-Alpes-Côte d'Azur": ["Marseille", "Nice", "Toulon", "Aix-en-Provence", "Antibes"],
        "Auvergne-Rhône-Alpes": ["Lyon", "Saint-Étienne", "Grenoble", "Villeurbanne", "Clermont-Ferrand"],
        "Nouvelle-Aquitaine": ["Bordeaux", "Limoges", "Poitiers", "Pau", "La Rochelle"],
        "Occitania": ["Toulouse", "Montpellier", "Nîmes", "Perpignan", "Béziers"],
        "Hauts-de-France": ["Lille", "Amiens", "Tourcoing", "Roubaix", "Dunkirk"],
        "Normandy": ["Le Havre", "Rouen", "Caen", "Cherbourg", "Évreux"],
        "Grand Est": ["Strasbourg", "Metz", "Nancy", "Reims", "Mulhouse"],
        "Pays de la Loire": ["Nantes", "Angers", "Le Mans", "Saint-Nazaire", "Laval"],
        "Brittany": ["Rennes", "Brest", "Quimper", "Lorient", "Vannes"],
        "Bourgogne-Franche-Comté": ["Dijon", "Besançon", "Belfort", "Chalon-sur-Saône", "Nevers"],
        "Centre-Val de Loire": ["Orléans", "Tours", "Bourges", "Blois", "Chartres"],
        "Corsica": ["Ajaccio", "Bastia", "Porto-Vecchio", "Corte", "Calvi"]
    },

    "Brazil": {
        "Acre": ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá", "Feijó", "Brasileia", "Plácido de Castro", "Xapuri", "Epitaciolândia", "Senador Guiomard"],
        "Alagoas": ["Maceió", "Arapiraca", "Palmeira dos Índios", "Rio Largo", "Penedo", "União dos Palmares", "São Miguel dos Campos", "Coruripe", "Delmiro Gouveia", "Santana do Ipanema"],
        "Amapá": ["Macapá", "Santana", "Laranjal do Jari", "Oiapoque", "Mazagão", "Porto Grande", "Pedra Branca do Amapari", "Vitória do Jari", "Tartarugalzinho", "Amapá"],
        "Amazonas": ["Manaus", "Parintins", "Itacoatiara", "Manacapuru", "Coari", "Tefé", "Tabatinga", "Maués", "São Gabriel da Cachoeira", "Humaitá"],
        "Bahia": ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Juazeiro", "Itabuna", "Lauro de Freitas", "Ilhéus", "Jequié", "Teixeira de Freitas"],
        "Ceará": ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú", "Sobral", "Crato", "Itapipoca", "Maranguape", "Iguatu", "Quixadá"],
        "Distrito Federal": ["Brasília", "Gama", "Taguatinga", "Ceilândia", "Sobradinho", "Planaltina", "São Sebastião", "Recanto das Emas", "Santa Maria", "Samambaia"],
        "Espírito Santo": ["Vitória", "Vila Velha", "Cariacica", "Serra", "Cachoeiro de Itapemirim", "Linhares", "São Mateus", "Colatina", "Guarapari", "Aracruz"],
        "Goiás": ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde", "Luziânia", "Águas Lindas de Goiás", "Valparaíso de Goiás", "Trindade", "Formosa", "Novo Gama"],
        "Maranhão": ["São Luís", "Imperatriz", "São José de Ribamar", "Timon", "Caxias", "Codó", "Paço do Lumiar", "Açailândia", "Bacabal", "Balsas"],
        "Mato Grosso": ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop", "Tangará da Serra", "Cáceres", "Sorriso", "Lucas do Rio Verde", "Barra do Garças", "Primavera do Leste"],
        "Mato Grosso do Sul": ["Campo Grande", "Dourados", "Três Lagoas", "Corumbá", "Ponta Porã", "Naviraí", "Nova Andradina", "Sidrolândia", "Maracaju", "São Gabriel do Oeste"],
        "Minas Gerais": ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim", "Montes Claros", "Ribeirão das Neves", "Uberaba", "Governador Valadares", "Ipatinga"],
        "Pará": ["Belém", "Ananindeua", "Santarém", "Marabá", "Parauapebas", "Castanhal", "Abaetetuba", "Cametá", "Marituba", "Bragança"],
        "Paraíba": ["João Pessoa", "Campina Grande", "Santa Rita", "Patos", "Bayeux", "Sousa", "Cajazeiras", "Cabedelo", "Guarabira", "Mamanguape"],
        "Paraná": ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel", "São José dos Pinhais", "Foz do Iguaçu", "Colombo", "Guarapuava", "Paranaguá"],
        "Pernambuco": ["Recife", "Jaboatão dos Guararapes", "Olinda", "Bandeira", "Caruaru", "Petrolina", "Paulista", "Cabo de Santo Agostinho", "Camaragibe", "Garanhuns"],
        "Piauí": ["Teresina", "Parnaíba", "Picos", "Piripiri", "Floriano", "Campo Maior", "Barras", "União", "Altos", "Pedro II"],
        "Rio de Janeiro": ["Rio de Janeiro", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu", "Niterói", "Campos dos Goytacazes", "Belford Roxo", "São João de Meriti", "Petrópolis", "Volta Redonda"],
        "Rio Grande do Norte": ["Natal", "Mossoró", "Parnamirim", "São Gonçalo do Amarante", "Macaíba", "Ceará-Mirim", "Caicó", "Assu", "Currais Novos", "Nova Cruz"],
        "Rio Grande do Sul": ["Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas", "Santa Maria", "Gravataí", "Viamão", "Novo Hamburgo", "São Leopoldo", "Rio Grande"],
        "Rondônia": ["Porto Velho", "Ji-Paraná", "Ariquemes", "Vilhena", "Cacoal", "Rolim de Moura", "Guajará-Mirim", "Jaru", "Ouro Preto do Oeste", "Buritis"],
        "Roraima": ["Boa Vista", "Rorainópolis", "Caracaraí", "Alto Alegre", "Mucajaí", "Iracema", "Amajari", "Bonfim", "Cantá", "Normandia"],
        "Santa Catarina": ["Joinville", "Florianópolis", "Blumenau", "São José", "Criciúma", "Chapecó", "Itajaí", "Lages", "Jaraguá do Sul", "Palhoça"],
        "São Paulo": ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André", "Osasco", "Ribeirão Preto", "Sorocaba", "Mauá", "São José dos Campos"],
        "Sergipe": ["Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana", "São Cristóvão", "Estância", "Tobias Barreto", "Simão Dias", "Propriá", "Canindé de São Francisco"],
        "Tocantins": ["Palmas", "Araguaína", "Gurupi", "Porto Nacional", "Paraíso do Tocantins", "Colinas do Tocantins", "Guaraí", "Formoso do Araguaia", "Dianópolis", "Tocantinópolis"]
    },

    "Mexico": {
        "Aguascalientes": ["Aguascalientes", "Jesús María", "Calvillo", "Rincón de Romos", "Asientos", "Tepezalá", "El Llano", "Cosío", "San José de Gracia", "Pabellón de Arteaga"],
        "Baja California": ["Tijuana", "Mexicali", "Ensenada", "Playas de Rosarito", "Tecate", "San Felipe", "Valle de Guadalupe", "La Rumorosa", "Bahía de los Ángeles", "San Quintín"],
        "Baja California Sur": ["La Paz", "Los Cabos", "Loreto", "Comondú", "Mulegé", "Santa Rosalía", "Ciudad Constitución", "San José del Cabo", "Cabo San Lucas", "Todos Santos"],
        "Campeche": ["Campeche", "Ciudad del Carmen", "Champotón", "Escárcega", "Calkiní", "Hecelchakán", "Hopelchén", "Palizada", "Tenabo", "Calakmul"],
        "Chiapas": ["Tuxtla Gutiérrez", "Tapachula", "San Cristóbal de las Casas", "Comitán de Domínguez", "Palenque", "Tonalá", "Arriaga", "Villaflores", "Pichucalco", "Yajalón"],
        "Chihuahua": ["Chihuahua", "Ciudad Juárez", "Delicias", "Parral", "Cuauhtémoc", "Nuevo Casas Grandes", "Camargo", "Jiménez", "Bocoyna", "Guachochi"],
        "Coahuila": ["Saltillo", "Torreón", "Monclova", "Piedras Negras", "Acuña", "Sabinas", "Matamoros", "San Pedro", "Frontera", "Francisco I. Madero"],
        "Colima": ["Colima", "Manzanillo", "Tecomán", "Villa de Álvarez", "Armería", "Coquimatlán", "Cuauhtémoc", "Ixtlahuacán", "Minatitlán", "Comala"],
        "Durango": ["Durango", "Gómez Palacio", "Lerdo", "Santiago Papasquiaro", "Guadalupe Victoria", "El Salto", "Canatlán", "Nombre de Dios", "Mezquital", "Peñón Blanco"],
        "Guanajuato": ["León", "Irapuato", "Celaya", "Salamanca", "Guanajuato", "Silao", "Pénjamo", "San Francisco del Rincón", "Acámbaro", "Valle de Santiago"],
        "Guerrero": ["Acapulco", "Chilpancingo", "Iguala", "Taxco", "Zihuatanejo", "Tlapa de Comonfort", "Ciudad Altamirano", "Ayutla de los Libres", "Ometepe", "Petatlán"],
        "Hidalgo": ["Pachuca", "Tulancingo", "Tizayuca", "Huejutla", "Ixmiquilpan", "Actopan", "Tula de Allende", "Tepeji del Río", "Apan", "Mineral de la Reforma"],
        "Jalisco": ["Guadalajara", "Zapopan", "Tlaquepaque", "Tonalá", "Puerto Vallarta", "Tlajomulco de Zúñiga", "El Salto", "Tepatitlán de Morelos", "Lagos de Moreno", "Ocotlán"],
        "Mexico": ["Ecatepec", "Nezahualcóyotl", "Naucalpan", "Tlalnepantla", "Chimalhuacán", "Toluca", "Atizapán de Zaragoza", "Cuautitlán Izcalli", "Ixtapaluca", "Valle de Chalco"],
        "Mexico City": ["Mexico City", "Iztapalapa", "Gustavo A. Madero", "Álvaro Obregón", "Tlalpan", "Coyoacán", "Xochimilco", "Iztacalco", "Miguel Hidalgo", "Venustiano Carranza"],
        "Michoacán": ["Morelia", "Uruapan", "Lázaro Cárdenas", "Zamora", "Apatzingán", "Hidalgo", "La Piedad", "Pátzcuaro", "Sahuayo", "Zitácuaro"],
        "Morelos": ["Cuernavaca", "Jiutepec", "Temixco", "Cuautla", "Yautepec", "Emiliano Zapata", "Xochitepec", "Zacatepec", "Jojutla", "Ayala"],
        "Nayarit": ["Tepic", "Bahía de Banderas", "Santiago Ixcuintla", "Tuxpan", "Compostela", "Ixtlán del Río", "Acaponeta", "Tecuala", "San Blas", "Rosamorada"],
        "Nuevo León": ["Monterrey", "Guadalupe", "San Nicolás de los Garza", "Apodaca", "General Escobedo", "Santa Catarina", "San Pedro Garza García", "Cadereyta Jiménez", "García", "Juárez"],
        "Oaxaca": ["Oaxaca de Juárez", "San Juan Bautista Tuxtepec", "Juchitán de Zaragoza", "Salina Cruz", "Huajuapan de León", "Puerto Escondido", "Tehuantepec", "Pinotepa Nacional", "Miahuatlán de Porfirio Díaz", "Tlaxiaco"],
        "Puebla": ["Puebla", "Tehuacán", "San Martín Texmelucan", "Atlixco", "San Pedro Cholula", "Amozoc", "Huauchinango", "Zacatlán", "Izúcar de Matamoros", "Tecamachalco"],
        "Querétaro": ["Santiago de Querétaro", "San Juan del Río", "Corregidora", "El Marqués", "Cadereyta de Montes", "Pedro Escobedo", "Tequisquiapan", "Jalpan de Serra", "Landa de Matamoros", "Amealco de Bonfil"],
        "Quintana Roo": ["Cancún", "Chetumal", "Playa del Carmen", "Cozumel", "Felipe Carrillo Puerto", "José María Morelos", "Lázaro Cárdenas", "Bacalar", "Tulum", "Akumal"],
        "San Luis Potosí": ["San Luis Potosí", "Soledad de Graciano Sánchez", "Ciudad Valles", "Matehuala", "Rioverde", "Tamazunchale", "Cárdenas", "Ebano", "Cerritos", "Villa de Reyes"],
        "Sinaloa": ["Culiacán", "Mazatlán", "Ahome", "Guasave", "Navolato", "El Fuerte", "Escuinapa", "Salvador Alvarado", "Angostura", "Mocorito"],
        "Sonora": ["Hermosillo", "Ciudad Obregón", "Nogales", "San Luis Río Colorado", "Navojoa", "Guaymas", "Agua Prieta", "Caborca", "Puerto Peñasco", "Cananea"],
        "Tabasco": ["Villahermosa", "Cárdenas", "Comalcalco", "Huimanguillo", "Macuspana", "Cunduacán", "Paraíso", "Jalpa de Méndez", "Nacajuca", "Emiliano Zapata"],
        "Tamaulipas": ["Reynosa", "Matamoros", "Nuevo Laredo", "Tampico", "Victoria", "Altamira", "Ciudad Madero", "Río Bravo", "Mante", "Valle Hermoso"],
        "Tlaxcala": ["Tlaxcala", "Apizaco", "Huamantla", "San Pablo del Monte", "Chiautempan", "Zacatelco", "Panotla", "Santa Cruz Tlaxcala", "Totolac", "La Magdalena Tlaltelulco"],
        "Veracruz": ["Veracruz", "Xalapa", "Coatzacoalcos", "Córdoba", "Poza Rica", "Minatitlán", "Orizaba", "Boca del Río", "Tuxpan", "Martínez de la Torre"],
        "Yucatán": ["Mérida", "Kanasín", "Umán", "Progreso", "Valladolid", "Tizimín", "Motul", "Tekax", "Hunucmá", "Ticul"],
        "Zacatecas": ["Zacatecas", "Fresnillo", "Guadalupe", "Jerez", "Río Grande", "Sombrerete", "Ojocaliente", "Loreto", "Pinos", "Luis Moya"]
    },

    "Japan": {
        "Aichi": ["Nagoya", "Toyota", "Okazaki", "Ichinomiya", "Seto", "Kasugai", "Inuyama", "Konan", "Komaki", "Inazawa"],
        "Akita": ["Akita", "Yokote", "Daisen", "Yurihonjo", "Odate", "Kazuno", "Kitaakita", "Nikaho", "Semboku", "Katagami"],
        "Aomori": ["Aomori", "Hirosaki", "Hachinohe", "Kuroishi", "Goshogawara", "Towada", "Misawa", "Mutsu", "Tsugaru", "Hirakawa"],
        "Chiba": ["Chiba", "Funabashi", "Matsudo", "Ichikawa", "Kashiwa", "Ichihara", "Kamagaya", "Narashino", "Yachiyo", "Abiko"],
        "Ehime": ["Matsuyama", "Imabari", "Niihama", "Saijo", "Ozu", "Uwajima", "Yawatahama", "Shikokuchuo", "Seiyo", "Toon"],
        "Fukui": ["Fukui", "Tsuruga", "Obama", "Ono", "Katsuyama", "Sabae", "Awara", "Echizen", "Sakai", "Ikeda"],
        "Fukuoka": ["Fukuoka", "Kitakyushu", "Kurume", "Omuta", "Iizuka", "Tagawa", "Yanagawa", "Yame", "Chikugo", "Okawa"],
        "Fukushima": ["Fukushima", "Koriyama", "Iwaki", "Shirakawa", "Sukagawa", "Kitakata", "Soma", "Nihonmatsu", "Tamura", "Minamisoma"],
        "Gifu": ["Gifu", "Ogaki", "Takayama", "Tajimi", "Seki", "Nakatsugawa", "Mizunami", "Hashima", "Minokamo", "Toki"],
        "Gunma": ["Maebashi", "Takasaki", "Kiryu", "Isesaki", "Ota", "Numata", "Tatebayashi", "Shibukawa", "Fujioka", "Tomioka"],
        "Hiroshima": ["Hiroshima", "Fukuyama", "Kure", "Higashihiroshima", "Hatsukaichi", "Mihara", "Onomichi", "Miyoshi", "Shobara", "Otake"],
        "Hokkaido": ["Sapporo", "Asahikawa", "Hakodate", "Kushiro", "Tomakomai", "Otaru", "Ebetsu", "Kitami", "Obihiro", "Iwamizawa"],
        "Hyogo": ["Kobe", "Himeji", "Nishinomiya", "Amagasaki", "Akashi", "Kakogawa", "Takarazuka", "Itami", "Sanda", "Ashiya"],
        "Ibaraki": ["Mito", "Tsukuba", "Hitachi", "Tsuchiura", "Koga", "Ishioka", "Ryugasaki", "Shimotsuma", "Hitachiota", "Takahagi"],
        "Ishikawa": ["Kanazawa", "Hakusan", "Komatsu", "Kaga", "Nanao", "Suzu", "Noto", "Kahoku", "Uchinada", "志賀"],
        "Iwate": ["Morioka", "Ichinoseki", "Rikuzentakata", "Ofunato", "Hanamaki", "Kitakami", "Kuji", "Tono", "Miyako", "Oshu"],
        "Kagawa": ["Takamatsu", "Marugame", "Sakaide", "Zentsuji", "Kanonji", "Sanuki", "Higashikagawa", "Mitoyo", "Ayagawa", "Utazu"],
        "Kagoshima": ["Kagoshima", "Kanoya", "Makurazaki", "Akune", "Izumi", "Ibusuki", "Nishinoomote", "Tarumizu", "Satsumasendai", "Hioki"],
        "Kanagawa": ["Yokohama", "Kawasaki", "Sagamihara", "Fujisawa", "Chigasaki", "Hiratsuka", "Odawara", "Atsugi", "Yamato", "Isehara"],
        "Kochi": ["Kochi", "Muroto", "Aki", "Nankoku", "Tosa", "Susaki", "Sukumo", "Tosashimizu", "Shimanto", "Konan"],
        "Kumamoto": ["Kumamoto", "Yatsushiro", "Arao", "Tamana", "Hitoyoshi", "Kamiamakusa", "Uki", "Aso", "Amakusa", "Koshi"],
        "Kyoto": ["Kyoto", "Fukuchiyama", "Maizuru", "Ayabe", "Uji", "Miyazu", "Kameoka", "Joyo", "Muko", "Nagaokakyo"],
        "Mie": ["Tsu", "Yokkaichi", "Matsusaka", "Kuwana", "Suzuka", "Nabari", "Owase", "Iga", "Kisosaki", "Shima"],
        "Miyagi": ["Sendai", "Ishinomaki", "Shiogama", "Kesennuma", "Shiroishi", "Natori", "Kakuda", "Tagajo", "Iwanuma", "Tome"],
        "Miyazaki": ["Miyazaki", "Miyakonojo", "Nobeoka", "Nichinan", "Kobayashi", "Hyuga", "Kushima", "Saito", "Ebino", "Takaharu"],
        "Nagano": ["Nagano", "Matsumoto", "Ueda", "Iida", "Suwa", "Komagane", "Iiyama", "Komoro", "Ina", "Okaya"],
        "Nagasaki": ["Nagasaki", "Sasebo", "Shimabara", "Isahaya", "Omura", "Hirado", "Matsuura", "Tsushima", "Iki", "Goto"],
        "Nara": ["Nara", "Kashihara", "Ikoma", "Yamatokoriyama", "Yamatotakada", "Sakurai", "Gojo", "Uda", "Kashiba", "Katano"],
        "Niigata": ["Niigata", "Nagaoka", "Joetsu", "Kashiwazaki", "Shibata", "Ojiya", "Kamo", "Tokamachi", "Mitsuke", "Murakami"],
        "Oita": ["Oita", "Beppu", "Nakatsu", "Hita", "Saiki", "Usuki", "津久見", "Taketa", "Bungoono", "Kitsuki"],
        "Okayama": ["Okayama", "Kurashiki", "Tsuyama", "Tamano", "Kasaoka", "Ibara", "Soja", "Takahashi", "Niimi", "Bizen"],
        "Okinawa": ["Naha", "Ginowan", "Okinawa", "Urasoe", "Nago", "Itoman", "Tomigusuku", "Uruma", "Miyakojima", "Nanjo"],
        "Osaka": ["Osaka", "Sakai", "Higashiosaka", "Hirakata", "Toyonaka", "Suita", "Takatsuki", "Yao", "Neyagawa", "Kishiwada"],
        "Saga": ["Saga", "Karatsu", "Tosu", "Taku", "Imari", "Takeo", "Kashima", "Ogi", "Ureshino", "Kanzaki"],
        "Saitama": ["Saitama", "Kawaguchi", "Kawagoe", "Tokorozawa", "Koshigaya", "Ageo", "Kasukabe", "Kumagaya", "Warabi", "Toda"],
        "Shiga": ["Otsu", "Hikone", "Nagahama", "Omihachiman", "Kusatsu", "Moriyama", "Ritto", "Konan", "Takashima", "Higashiomi"],
        "Shimane": ["Matsue", "Hamada", "Izumo", "Masuda", "Oda", "Gotsu", "Yasugi", "Unnan", "Ama", "Kawamoto"],
        "Shizuoka": ["Shizuoka", "Hamamatsu", "Numazu", "Atami", "Mishima", "Fujinomiya", "Ito", "Shimada", "Fuji", "Iwata"],
        "Tochigi": ["Utsunomiya", "Ashikaga", "Tochigi", "Sano", "Kanuma", "Nikko", "Oyama", "Moka", "Ohtawara", "Yaita"],
        "Tokushima": ["Tokushima", "Naruto", "Komatsushima", "Anan", "Yoshinogawa", "Awa", "Mima", "Miyoshi", "Kamikatsu", "Katsuura"],
        "Tokyo": ["Tokyo", "Hachioji", "Tachikawa", "Musashino", "Mitaka", "Ome", "Fuchu", "Akishima", "Chofu", "Machida"],
        "Tottori": ["Tottori", "Yonago", "Kurayoshi", "Sakaiminato", "Iwami", "Hoki", "Chizu", "Wakasa", "Yurihama", "Misasa"],
        "Toyama": ["Toyama", "Takaoka", "Uozu", "Himi", "Namerikawa", "Kurobe", "Tonami", "Oyabe", "Nanto", "Imizu"],
        "Wakayama": ["Wakayama", "Tanabe", "Hashimoto", "Arida", "Gobo", "Shingu", "Kinokawa", "Iwade", "Kainan", "Katsuragi"],
        "Yamagata": ["Yamagata", "Tsuruoka", "Sakata", "Shinjo", "Sagae", "Kaminoyama", "Murayama", "Nagai", "Tendo", "Higashine"],
        "Yamaguchi": ["Yamaguchi", "Shimonoseki", "Ube", "Yamaguchi", "Hagi", "Hofu", "Kudamatsu", "Iwakuni", "Hikari", "Nagato"],
        "Yamanashi": ["Kofu", "Fujiyoshida", "Tsuru", "Yamanashi", "Otsuki", "Nirasaki", "Minami-Alps", "Hokuto", "Kai", "Fuefuki"]
    },

    "Argentina": {
        "Buenos Aires": ["Buenos Aires", "La Plata", "Mar del Plata", "Bahía Blanca", "Tandil", "Olavarría", "Pergamino", "Junín", "Azul", "Necochea"],
        "Catamarca": ["San Fernando del Valle de Catamarca", "Andalgalá", "Belén", "Santa María", "Tinogasta", "Fiambalá", "Londres", "Recreo", "Valle Viejo", "Fray Mamerto Esquiú"],
        "Chaco": ["Resistencia", "Barranqueras", "Fontana", "Puerto Vilelas", "Presidencia Roque Sáenz Peña", "Villa Ángela", "Charata", "General José de San Martín", "Machagai", "Quitilipi"],
        "Chubut": ["Rawson", "Comodoro Rivadavia", "Puerto Madryn", "Trelew", "Esquel", "Puerto Deseado", "Dolavon", "Gaiman", "Cholila", "El Bolsón"],
        "Córdoba": ["Córdoba", "Villa María", "Río Cuarto", "San Francisco", "Villa Carlos Paz", "Alta Gracia", "Jesús María", "Marcos Juárez", "Bell Ville", "Cruz del Eje"],
        "Corrientes": ["Corrientes", "Goya", "Paso de los Libres", "Mercedes", "Curuzú Cuatiá", "Monte Caseros", "Esquina", "Santo Tomé", "Bella Vista", "Saladas"],
        "Entre Ríos": ["Paraná", "Concordia", "Gualeguaychú", "Concepción del Uruguay", "Victoria", "Villaguay", "Chajarí", "La Paz", "Crespo", "Colón"],
        "Formosa": ["Formosa", "Clorinda", "Pirané", "El Colorado", "Ingeniero Juárez", "Las Lomitas", "Comandante Fontana", "Ibarreta", "Laguna Blanca", "Pozo del Tigre"],
        "Jujuy": ["San Salvador de Jujuy", "Palpalá", "Libertador General San Martín", "Perico", "San Pedro", "Humahuaca", "La Quiaca", "Tilcara", "Abra Pampa", "Calilegua"],
        "La Pampa": ["Santa Rosa", "General Pico", "Toay", "Realicó", "Eduardo Castex", "Intendente Alvear", "Guatraché", "Macachín", "Victorica", "General Acha"],
        "La Rioja": ["La Rioja", "Chilecito", "Aimogasta", "Chamical", "Chepes", "Villa Unión", "Nonogasta", "Famatina", "Patquía", "Sanagasta"],
        "Mendoza": ["Mendoza", "San Rafael", "Godoy Cruz", "Guaymallén", "Las Heras", "Maipú", "Luján de Cuyo", "San Martín", "Rivadavia", "Junín"],
        "Misiones": ["Posadas", "Oberá", "Eldorado", "Puerto Iguazú", "Apóstoles", "Leandro N. Alem", "Montecarlo montecarlo", "Puerto Rico", "Jardín América", "Aristóbulo del Valle"],
        "Neuquén": ["Neuquén", "Plottier", "Cipolletti", "Cutral Có", "Centenario", "Villa La Angostura", "San Martín de los Andes", "Zapala", "Rincón de los Sauces", "Chos Malal"],
        "Río Negro": ["Viedma", "San Carlos de Bariloche", "General Roca", "Cipolletti", "Villa Regina", "Río Colorado", "Allen", "Catriel", "El Bolsón", "Ingeniero Jacobacci"],
        "Salta": ["Salta", "San Ramón de la Nueva Orán", "Tartagal", "Metán", "Cafayate", "General Güemes", "Rosario de Lerma", "Embarcación", "Joaquín V. González", "El Carmen"],
        "San Juan": ["San Juan", "Rawson", "Chimbas", "Rivadavia", "Santa Lucía", "Pocito", "San Martín", "Caucete", "9 de Julio", "Albardón"],
        "San Luis": ["San Luis", "Villa Mercedes", "Merlo", "Tilisarao", "Justo Daract", "La Toma", "Concarán", "Villa de la Quebrada", "Naschel", "Candelaria"],
        "Santa Cruz": ["Río Gallegos", "Caleta Olivia", "Pico Truncado", "Puerto Deseado", "Puerto San Julián", "El Calafate", "28 de Noviembre", "Las Heras", "Gobernador Gregores", "Puerto Santa Cruz"],
        "Santa Fe": ["Santa Fe", "Rosario", "Villa Gobernador Gálvez", "Venado Tuerto", "Rafaela", "Reconquista", "Santo Tomé", "Esperanza", "San Lorenzo", "Casilda"],
        "Santiago del Estero": ["Santiago del Estero", "La Banda", "Termas de Río Hondo", "Añatuya", "Frías", "Monte Quemado", "Fernández", "Clodomira", "Quimilí", "Bandera"],
        "Tierra del Fuego": ["Ushuaia", "Río Grande", "Tolhuin", "Puerto Almanza", "Puerto Williams", "Estancia Harberton", "Porvenir", "Cameron", "Cerro Sombrero", "Primavera"],
        "Tucumán": ["San Miguel de Tucumán", "Yerba Buena", "Tafí Viejo", "Banda del Río Salí", "Concepción", "Aguilares", "Monteros", "Famaillá", "Alderetes", "Juan Bautista Alberdi"]
    }
};